.ɵɵelementStart(-1, "div") // SOURCE: "/escaped_chars.html" "<div>\r\n  "
…
.ɵɵtext(1, " Some Message Encoded character: \uD83D\uDE80\\n") // SOURCE: "/escaped_chars.html" "Some Message\r\n  Encoded character: 🚀\r\n"
…
.ɵɵelementEnd() // SOURCE: "/escaped_chars.html" "</div>"
