i0.ɵɵelementStart(-1, "h3") // SOURCE: "/projection.ts" "<h3>"
…
i0.ɵɵprojection(1) // SOURCE: "/projection.ts" "<ng-content select=\"title\"></ng-content>"
…
i0.ɵɵelementEnd() // SOURCE: "/projection.ts" "</h3>"
…
i0.ɵɵelementStart(-3, "div") // SOURCE: "/projection.ts" "<div>"
…
i0.ɵɵprojection(3, 1) // SOURCE: "/projection.ts" "<ng-content></ng-content>"
…
i0.ɵɵelementEnd() // SOURCE: "/projection.ts" "</div>"
