.ɵɵelementStart(-1, "h3") // SOURCE: "/projection.ts" "<h3>"
…
.ɵɵprojection(1) // SOURCE: "/projection.ts" "<ng-content select="title"></ng-content>"
…
.ɵɵelementEnd() // SOURCE: "/projection.ts" "</h3>\n  "
…
.ɵɵelementStart(-3, "div") // SOURCE: "/projection.ts" "<div>"
…
.ɵɵprojection(3, 1) // SOURCE: "/projection.ts" "<ng-content></ng-content>"
…
.ɵɵelem // SOURCE: "/projection.ts" "</div>`"
